### ISSUE TITLE
current,navdata isn't loaded.

### ISSUE THREAD

**Issue by boruto-300** [nickchen120235/msfs-rjda-navdata#1]
worldmap won't load navdata. 
May i fix it?or, Would you update this?

**Comment by nickchen120235** [comment]
![image](https://github.com/nickchen120235/msfs-rjda-navdata/assets/45678482/e8be67a6-10c4-49a5-b109-0daff4304dbf)

![image](https://github.com/nickchen120235/msfs-rjda-navdata/assets/45678482/5979bf4a-87d6-4a2a-a7e4-e056785fece7)

I think it works? Can you try reinstalling the add-on?

**Comment by boruto-300** [comment]
thank you for reply.
I'll try again.

**Comment by boruto-300** [comment]
it works.I just mistook method to put it folder.
